### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by aranyasinha** [toxicmender/monsters#3]
Cut down on the extraneous documentaion

**Comment by Danpar97** [comment]
Can you be more specifc?
README.md?
Contributing.md?

**Comment by aranyasinha** [comment]
Contributing.MD mainly

**Comment by aranyasinha** [comment]
Also, get rid of CODE_OF_CONDUCT.md. We are only two people.

**Comment by toxicmender** [comment]
review the changes @aranyasinha
